settings:
  APP_DISPLAY_NAME: Pareza
  PRODUCTION_APP_NAME: Pareza
  APP_GROUP_IDENTIFIER: group.com.parezaapp
  BASE_BUNDLE_IDENTIFIER: com.parezaapp.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 6J72UHVN5X
